### ISSUE TITLE
Sketch fails to compile, prog_char has not been declared

### ISSUE THREAD

**Issue by SanderP** [AE9RB/iambino#1]
Hi,

I ordered your shield and a new Uno. I figured I'd program it so the Uno is ready for when the shield gets here tomorrow or the day after. I get this error:

iambino:63: error: 'prog_char' has not been declared
lcd:19: error: 'prog_char' does not name a type
lcd:29: error: 'prog_char' does not name a type
lcd:39: error: 'prog_char' does not name a type
lcd:49: error: 'prog_char' has not been declared
lcd.ino: In function 'void lcd_setup()':
lcd:66: error: 'lcd_box' was not declared in this scope
lcd:67: error: 'lcd_left_arrow' was not declared in this scope
lcd:68: error: 'lcd_right_arrow' was not declared in this scope
'prog_char' has not been declared

Do I need to add an LCD library to my Arduino install?

Thanks,

   Sander W1SOP

**Comment by AE9RB** [comment]
c0f908151d9dad8c580c06a8951bc0be6dac2f76

**Comment by SanderP** [comment]
Fix confirmed, thanks!
